Generators and api functions
WebUraXalys/blackout pull request #21
Opened 2023-05-10 13:01 UTC by WebUraXalys

Creted "genererators.py" with functions "generate_plan_interruption", "generate_emergency_interruption" and "generate_planed_interrupted_buildings", added buttons in Django admin with them functionality.

Created "api.py" with function "send_buildings_coordinates".

2023-05-10 13:04 UTC, Prohodchikoff commented on blackout/blackout/settings.py
> +SECRET_KEY = 'a'
SECRET_KEY = [os.getenv('SERVER_URL'), '127.0.0.1']

2023-05-15 13:06 UTC, Prohodchikoff requested changes

2023-05-15 21:35 UTC, Ferkkkk commented on blackout/parserapp/services/generators.py
> +
https://github.com/WebUraXalys/blackout/pull/21/commits/a238161dea6333e28bf21ab5d557a69a3497f364

2023-05-15 21:36 UTC, Ferkkkk commented on blackout/blackout/settings.py
> +SECRET_KEY = 'a'
https://github.com/WebUraXalys/blackout/pull/21/commits/a238161dea6333e28bf21ab5d557a69a3497f364

2023-05-22 12:44 UTC, WebUraXalys commented
Can you describe the API link as an authorized pull request

2023-05-27 19:57 UTC, Prohodchikoff requested changes
Fix the issue

2023-05-31 22:33 UTC, Ferkkkk commented
> Fix the issue
https://github.com/WebUraXalys/blackout/commit/cbf7e1ab906b690c4a7d2b8efd222db206582708

2023-09-23 14:10 UTC, closed without merging